### ISSUE TITLE
Not able to fetch DTR questionnaire 

### ISSUE THREAD

**Issue by sijoxavier89** [HL7-DaVinci/prior-auth#185]
![image](https://user-images.githubusercontent.com/25562242/168094376-d224b94a-23c3-4e85-a379-7fc70c05dc77.png)

after setting up the docker containers , submitted a request for Patient : William Oster, (E0470), clicking on the "Order Form" launches the SMART app but the questionnaire is not getting fetched. Wanted to confirm is this an existing issue .

**Comment by smalho01** [comment]
I thought this issue was fixed at the Connectathon, thanks for bringing this to my attention. @sijoxavier89 are you using one of the local set up options that uses docker containers?

**Comment by smalho01** [comment]
I've identified the issue - there was a code change that fixed this problem that was pushed to master, hence why this issue doesn't appear when running locally, however our docker image does not show that change in both my published version and the official logicahealth version. I will am investigating our ci-cd pipeline and look for a fix, will let you all know in this thread when the issue is resolved.

**Comment by anishtechnet** [comment]
@smalho01 : I deleted previous clone from my machine and tried to set it up from scratch following instructions in -- https://github.com/HL7-DaVinci/prior-auth/blob/dev/DockerDevSetupGuide.md

When I try to execute command  docker-compose -f docker-compose-dev.yml up --build --force-recreate, I am getting external volume "pas_dev_prior-auth-sync" not found message.

 If I try to run docker-compose up, command I am getting "Error response from daemon: manifest for smalho01234/crd2:latest not found: manifest unknown: manifest unknown" error message now.

**Comment by smalho01** [comment]
There are issues with our CI-CD pipeline, I am reaching out to GitHub and DockerHub to work through these issues. There's also an issue with CRD's codebase where it doesn't work in docker anymore and we are trying to figure that out as well. 

For the docker-compose-dev.yml issue, that is because there are external volumes defined in there which get set up by docker-sync. You should use the d`ocker-sync-stack start` command to use the developer environment if you guys are planning on making code changes on our repos (or forks of our repos). Otherwise, I would recomend following the local set up guide here: https://github.com/HL7-DaVinci/prior-auth/blob/dev/DockerLocalSetupGuide.md. 

For the tradition docker-compose.yml file which gets read when doing `docker-compose up` command, it is because I deleted the latest tag in an effort to debug the ci-cd pipeline issue. I have republished that image tag so that should fix that error you're seeing currently if you try again, however CRD will still have the issue that results in the original issue at the top of this thread. 

I'm working on this as best as I can and will definitely update you guys here once a solution has been reached and pushed/published, likely this won't be until sometime next week, in the mean time I thank you for your patience

**Comment by smalho01** [comment]
Status Update: We have figured out the issue with CRD which was causing the original issue and have figured out a solution there. I still need to clean up some thing relating to the dockerized environment and once I do the install should work as expected. I will let you guys know when that is all pushed up so you can try rerunning the dockerized DRLS + PAS environment. I'm going to aim for getting that in sometime this week and thank you again for your patience

**Comment by sijoxavier89** [comment]
@smalho01 just wanted to check with you. do we have the changes updated to docker images?
